language: php

php:
    - 7
    - 5.6
    - 5.5
    - 5.4

branches:
    only:
        - 1.x-dev
        - 2.x-dev

notifications:
    email: false

install:
    - composer install --dev

script:
    - php bin/phing phpunit
